Replacing usage of MRN
hmrc/declare-transit-movement-arrival-frontend pull request #234
Opened 2020-09-07 08:26 UTC by alexflav23

2020-09-07 11:15 UTC, amaalali requested changes
A few more thing that we need to address
- I don't think this works at the current moment, the data would be saved correctly but the user journey would immediately break on the next page. The SessionRepository would need to be updated since we now need to fetch by the `ArrivalUniqueRef` instead of the MRN (which is saved in the _id field)
- To protect the Session repository from these sort of breakages in the future I suggest that we change the `SessionRepository`'s `get` to be `def get(id: ArrivalUniqueRef, eoriNumber: EoriNumber): Future[Option[UserAnswers]]` 
- We'll need to add an index for the `ref` field in user-answers collection since this is used by the session repository for it's query. I would also recommend making this a unique.

2020-09-07 11:23 UTC, amaalali requested changes

2020-09-07 11:23 UTC, amaalali commented on app/models/ArrivalUniqueRef.scala
> +final case class ArrivalUniqueRef(uuid: UUID) {
Would `DraftArrivalRef` be a better name for this? It's not an arrival message as yet, just a in-progress draft at this point

2020-09-07 11:23 UTC, amaalali commented on app/models/UserAnswers.scala
> +        (__ \ "ref").write[ArrivalUniqueRef]
This Json Writes would result in a Json shape of:

```
{
    "_id" : "99IT9876AB88901209",
    "data" : {},
    "eoriNumber" : "GB1212",
    "lastUpdated" : ISODate("2020-09-07T12:01:42.109Z"),
    "ref" : {
        "uuid" : "893dca38-a174-4aa6-abc4-cc1ab158cd67"
    }
}
```

But I think this should be flattened out like:

```
{
    "_id" : "99IT9876AB88901209",
    "data" : {},
    "eoriNumber" : "GB1212",
    "lastUpdated" : ISODate("2020-09-07T12:01:42.109Z"),
    "draftArrivalRef" : "893dca38-a174-4aa6-abc4-cc1ab158cd67"
}
```

2020-09-21 14:39 UTC, chris-ianson commented on .g8/checkboxPage/migrations/$className__snake$.sh
> +echo "GET        /:mrn/$className;format="decap"$                        controllers.$className$Controller.onPageLoad(ref: MovementReferenceNumber, mode: Mode = NormalMode)" >> ../conf/app.routes
First argument needs to change to ArrivalUniqueRef

2020-09-21 14:39 UTC, chris-ianson commented on .g8/checkboxPage/migrations/$className__snake$.sh
> +echo "GET        /:mrn/change$className$                  controllers.$className$Controller.onPageLoad(ref: MovementReferenceNumber, mode: Mode = CheckMode)" >> ../conf/app.routes
First argument needs to change to ArrivalUniqueRef

2020-09-21 14:40 UTC, chris-ianson commented on .g8/checkboxPage/migrations/$className__snake$.sh
>  echo "POST       /:mrn/change$className$                  controllers.$className$Controller.onSubmit(mrn: MovementReferenceNumber, mode: Mode = CheckMode)" >> ../conf/app.routes
First argument needs to change to ArrivalUniqueRef

2020-09-21 14:40 UTC, chris-ianson commented on .g8/datePage/migrations/$className__snake$.sh
> +echo "GET        /:mrn/change$className$                        controllers.$className$Controller.onPageLoad(ref: MovementReferenceNumber, mode: Mode = CheckMode)" >> ../conf/app.routes
First argument needs to change to ArrivalUniqueRef

2020-09-21 14:40 UTC, chris-ianson commented on .g8/datePage/migrations/$className__snake$.sh
> +echo "GET        /:mrn/$className;format="decap"$                  controllers.$className$Controller.onPageLoad(ref: MovementReferenceNumber, mode: Mode = NormalMode)" >> ../conf/app.routes
First argument needs to change to ArrivalUniqueRef

2020-09-21 14:41 UTC, chris-ianson commented on .g8/datePage/migrations/$className__snake$.sh
>  echo "POST       /:mrn/$className;format="decap"$                  controllers.$className$Controller.onSubmit(mrn: MovementReferenceNumber, mode: Mode = NormalMode)" >> ../conf/app.routes
First argument needs to change to ArrivalUniqueRef

2020-09-21 14:41 UTC, chris-ianson commented on .g8/datePage/migrations/$className__snake$.sh
>  echo "POST       /:mrn/change$className$                        controllers.$className$Controller.onSubmit(mrn: MovementReferenceNumber, mode: Mode = CheckMode)" >> ../conf/app.routes
First argument needs to change to ArrivalUniqueRef

2020-09-21 14:41 UTC, chris-ianson commented on .g8/intPage/migrations/$className__snake$.sh
> +echo "GET        /:mrn/$className;format="decap"$                  controllers.$className$Controller.onPageLoad(ref: MovementReferenceNumber, mode: Mode = NormalMode)" >> ../conf/app.routes
First argument needs to change to ArrivalUniqueRef

2020-09-21 14:47 UTC, chris-ianson requested changes
The g8 templates that we use to build different pages are still referencing MRN so when new pages are created they won't work. Could we update all the templates to use ArrivalUniqueRef rather than MovemmentReferenceNumber

Also the following tests are failing:
- ArrivalRejectionControllerSpec

2020-09-29 14:32 UTC, closed without merging