Ctctraders 1606 - update validation and error messages
hmrc/declare-transit-movement-arrival-frontend pull request #293
Opened 2021-01-05 10:02 UTC by kenneth-rayner

2021-01-05 10:40 UTC, ashwinirudrappa reviewed
@kenneth-rayner Looks good a minor comment and do we have a test for the regesx changes

2021-01-05 10:40 UTC, ashwinirudrappa commented on app/models/domain/TraderDomain.scala
> +  val inputRegex: Regex = "[\\sa-zA-Z0-9&'*@/.\\-?<>]*".r
@kenneth-rayner The regex looks to be not allowing spaces but the messages allow spaces. Please recheck the regex

2021-01-05 14:19 UTC, PSouthern requested changes

2021-01-05 14:19 UTC, PSouthern commented on app/forms/TraderAddressFormProvider.scala
> +            Seq("town or city", traderName)
Instead of hardcoding this here, can this follow the same pattern as the other assertions and pass the constant instead?

i.e. `Address.Constants.Fields.city` and then update the constant to be `"town or city"` which will fix the copy issue for the other errors on this field as well.

2021-01-06 08:08 UTC, PSouthern approved these changes

2021-01-06 08:18 UTC, merged